repositories {
    maven {
        name = "Curios"
        url = uri("https://maven.theillusivec4.top/")
    }
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    implementation "net.sirgrantd:sg_economy:${sg_economy_version}"

    implementation "net.sirgrantd:celesthyd:${celesthyd_version}"
    jarJar "net.sirgrantd:celesthyd:${celesthyd_version}"

    runtimeOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}"
    compileOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}:api"
}